chat/chat/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('groups/', include('groups.urls', namespace="groups")),
    path('chats/', include('chats.urls', namespace="chats")),
    path('channels/', include('users_channels.urls', namespace="channels")),
    path('auth/', include('users.urls', namespace="users")),
    path('info/', include('info.urls', namespace="info")),
    path('', include('homepage.urls', namespace="homepage")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

chat/chats/urls.py
from django.urls import path

from chats.views import (ChatRedirectOrCreateView, ChatsListView, ChatView,
                         ClearChatMessagesConfirmView, ClearChatMessagesView)

app_name = 'chats'

urlpatterns = [
    path('',
         ChatsListView.as_view(),
         name='chats_list'),
    path('<int:chat_id>/',
         ChatView.as_view(),
         name='chat'),
    path('clear_messages_confirm/<int:chat_id>/',
         ClearChatMessagesConfirmView.as_view(),
         name='clear_messages_confirm'),
    path('clear_messages/<int:chat_id>/',
         ClearChatMessagesView.as_view(),
         name='clear_messages'),
    path('redirect_or_create/',
         ChatRedirectOrCreateView.as_view(),
         name='redirect_or_create'),
]

chat/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from users.views import ProfileView, SignupView, UserDetailView, UsersListView

app_name = 'users'

urlpatterns = [
    path('logout/',
         LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
    path('login/',
         LoginView.as_view(
             template_name='users/login.html'),
         name='login'),

    path('password_change/',
         PasswordChangeView.as_view(template_name='users/password_change.html'),
         name='password_change'),
    path('password_change/done/',
         PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),

    path('password_reset/',
         PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password_reset/done/',
         PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

    path('users/',
         UsersListView.as_view(),
         name='users_list'),
    path('users/<int:id>/',
         UserDetailView.as_view(),
         name='user_detail'),

    path('signup/',
         SignupView.as_view(),
         name='signup'),
    path('profile/',
         ProfileView.as_view(),
         name='profile'),
]

chat/chats/models.py
from django.contrib.auth import get_user_model
from django.db import models

from django.db.models import Q
from django.db.models.query import QuerySet


User = get_user_model()


class ChatManager(models.Manager):
    def get_chat_by_users(self,  first_user: User, second_user: User) -> QuerySet:
        return Chat.objects.filter(Q(first_user=first_user) & Q(second_user=second_user) |
                                   Q(first_user=second_user) & Q(second_user=first_user))


class Chat(models.Model):
    """
    Модель чат между двумя пользователями.

    Attributes:
        first_user (User): первый участник чата
        second_user (User): второй участник чата

    """
    first_user = models.ForeignKey(User,
                                   verbose_name='Первый пользователь чата',
                                   related_name='first_user_chats',
                                   on_delete=models.CASCADE)
    second_user = models.ForeignKey(User,
                                    verbose_name='Второй пользователь чата',
                                    related_name='second_user_chats',
                                    on_delete=models.CASCADE)

    def check_if_user_is_member(self, user: User) -> bool:
        """
        Проверяет, является ли пользователь участником чата

        Args:
            user (User): пользователь

        Returns:
            bool
        """
        return self.first_user.id == user.id or self.second_user.id == user.id

    objects = ChatManager()

    class Meta:
        verbose_name = 'Чат'
        verbose_name_plural = 'Чаты'

    def __str__(self):
        return f"Chat<{self.id}>"

chat/chats/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.handlers.asgi import ASGIRequest
from django.db.models.query import QuerySet
from django.shortcuts import get_object_or_404, render
from django.utils.decorators import method_decorator
from django.views.generic.base import RedirectView, TemplateView
from users_messages.models import DailyChatMessages
from websockets.connection_types import CHATS_CONNECTION

from chats.models import Chat

User = get_user_model()


@method_decorator(login_required, name='dispatch')
class ChatView(TemplateView):
    """
    Отображает модель Chat - список сообщений, панель редактирования и удаления чата,
    поле отправки сообщения

    Context:
        connection_type (str): тип подключения к вебсокетам
        is_member (bool): флаг, указывающий является ли пользователь участником чата
        user (User): экземпляр класса User
        chat (Chat): экземпляр класса Chat
        messages (UserChatMessage[]): сообщения чата

    Template:
        template_name: 'chats/chat.html'

    """

    template_name = 'chats/chat.html'

    def get(self, request: ASGIRequest, chat_id: int, *args, **kwargs):
        return render(request,
                      self.template_name,
                      self.get_context_data(request.user, chat_id))

    def get_context_data(self, user: User, chat_id: int, **kwargs):
        context = super().get_context_data(**kwargs)

        chat: Chat = get_object_or_404(Chat, pk=chat_id)

        context['connection_type'] = CHATS_CONNECTION
        context['chat'] = chat
        context['user'] = user
        context['is_member'] = False

        if chat.check_if_user_is_member(user):
            container, is_created = DailyChatMessages.objects.get_or_create(chat=chat)

            messages = container.get_messages()

            context['is_member'] = True
            context['chat'] = chat
            context['messages'] = messages

        return context


class ChatsListView(TemplateView):
    """
    Отображает список чатов (Chat)

    Context:
        chats (Chat[]): QuerySet содержащий экземпляры класса Chat

    Template:
        template_name: 'chats/chats_list.html'
    """

    template_name = 'chats/chats_list.html'

    def get(self, request: ASGIRequest, *args, **kwargs):
        return render(request,
                      self.template_name,
                      self.get_context_data(request.user))

    def get_context_data(self, user: User, **kwargs):
        context = super().get_context_data(**kwargs)

        # получаем чаты пользователя
        chats: QuerySet = user.first_user_chats.all() | user.second_user_chats.all()

        context['chats'] = chats
        return context


class ChatRedirectOrCreateView(RedirectView):
    """
    Перенаправляет пользователя на страницу чата.
    Если чата не существует, то он создается и пользователь также перенаправляется в чат.

    Pattern:
        pattern_name: 'chats:chat'

    """
    permanent = False
    query_string = True
    pattern_name = 'chats:chat'

    def get_redirect_url(self, *args, **kwargs):
        first_username = self.request.user.username
        second_username = self.request.GET.get('username')

        first_user = get_object_or_404(User, username=first_username)
        second_user = get_object_or_404(User, username=second_username)

        chats: QuerySet = Chat.objects.get_chat_by_users(first_user, second_user)
        if chats:
            chat = chats.first()
        else:
            chat = Chat(first_user=first_user, second_user=second_user)
            chat.save()

        return super().get_redirect_url(chat_id=chat.id)


@method_decorator(login_required, name='dispatch')
class ClearChatMessagesConfirmView(TemplateView):
    """
    Отображает модальное окно с подтверждением удаления истории сообщений

    Context:
        chat (Chat): экземпляр класса Chat

    Template:
        template_name: 'chats/clear_chat_messages_confirm.html'
    """

    template_name = 'chats/clear_chat_messages_confirm.html'

    def get(self, request: ASGIRequest, chat_id: int, *args, **kwargs):
        return render(request,
                      self.template_name,
                      self.get_context_data(chat_id))

    def get_context_data(self, chat_id: int, **kwargs):
        context = super().get_context_data(**kwargs)
        chat = get_object_or_404(Chat, pk=chat_id)
        context['chat'] = chat
        return context


@method_decorator(login_required, name='dispatch')
class ClearChatMessagesView(TemplateView):
    """
    Отображает страницу с сообщением об успешном удалении истории сообщений чата

    Context:
        chat (Chat): экземпляр класса Chat

    Template:
        template_name: 'chats/clear_chats_messages.html'
    """

    template_name = 'chats/clear_chats_messages.html'

    def get(self, request: ASGIRequest, chat_id: int, *args, **kwargs):
        chat: Chat = get_object_or_404(Chat, pk=chat_id)

        chat_container: DailyChatMessages = DailyChatMessages.objects.get(chat=chat)
        chat_container.chat_messages.all().delete()

        return render(request,
                      self.template_name,
                      self.get_context_data(chat_id))

    def get_context_data(self, chat_id: int, **kwargs):
        context = super().get_context_data(**kwargs)
        chat = get_object_or_404(Chat, pk=chat_id)
        context['chat'] = chat
        return context

chat/templates/chats/chat.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Чат {% endblock %}

{% block content %}
  {% include '../includes/sidebar.html' %}
    <div class='content col-xl-9 h-100'>
      {% if is_member %}
        {% include '../includes/clear_chat_messages_confirm.html' with chat=chat %}
        {% if request.user.id == chat.first_user.id %}
            <h1 class='title'>Чат с {{ chat.second_user.username }}</h1>
        {% else %}
            <h1 class='title'>Чат с {{ chat.first_user.username }}</h1>
        {% endif %}
        <div class='chat col-12'>
            <div class="chat__options">
              {% if request.user.id == chat.first_user.id %}
                  <a href='{% url "users:user_detail" chat.second_user.id %}' class='chat__user-link' title='{{ chat.second_user.username }}'>{{ chat.second_user.username|truncatechars:50 }}</a>
              {% else %}
                  <a href='{% url "users:user_detail" chat.first_user.id %}' class='chat__user-link' title='{{ chat.first_user.username }}'>{{ chat.first_user.username|truncatechars:50 }}</a>
              {% endif %}
                <a class='chat__clear-messages chat__clear-messages_in-chat'>
                  <svg viewBox="0 0 32 32"><path class="cls-1" d="M17.39,16l7.32-7.32a1,1,0,1,0-1.39-1.39L16,14.61,8.68,7.29A1,1,0,1,0,7.29,8.68L14.61,16,7.29,23.32a1,1,0,1,0,1.39,1.39L16,17.39l7.32,7.32a1,1,0,0,0,1.39-1.39Z"/><path d="M16,32A16,16,0,1,1,32,16,16,16,0,0,1,16,32ZM16,2A14,14,0,1,0,30,16,14,14,0,0,0,16,2Z"/></svg>  
                </a>
            </div>
           <div id='chat-log'>
              <span class='chat-log__title-message-container'>
                <span>
                ✨ Напишите первое сообщение! ✨
                </span>
              </span>
              {% for message in messages.all %}
                {% if message.user == user %}
                  <div class='message current-user-message'>
                    <span class='message__author'>
                      {{ message.user.username }} 
                    </span>
                    <p class='message__text'>{{ message.text|safe }}</p>
                    <span class='message__time'>{{ message.time }} </span>
                  </div>
                {% else %}
                  <div class='message'>
                    <span class='message__author'>
                      {{ message.user.username }} 
                    </span>
                    <p class='message__text'>{{message.text|safe}}</p>
                    <span class='message__time'>{{ message.time }} </span>
                  </div>
                {% endif %}
              {% endfor %}
            </div>
            <div class='chat__sendings'>
              <textarea 
                      id='chat-message-input'
                      maxlength='1024'
                      placeholder='Введите сообщение...'
                      rows='1'
                      ></textarea>
              <button id='chat-message-submit' title='Отправить сообщение'>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><polygon class="cls-1" points="30.58 16 1.42 2 8.42 16 1.42 30 30.58 16"/></svg>
              </button>
            </div>
        </div>
        <script type='text/javascript' src='{% static "js/auto_textarea_resizing.js" %}'></script>
        <script type='text/javascript' src='{% static "js/messages_confirmation_modal.js" %}'></script>
        {% include '../includes/websocket_data.html' with connection_type=connection_type connection_name=chat.id username=request.user.username %}
      {% else %}
        <h1 class='title'>Вы не состоите в этом чате 😔</h1>
      {% endif %}
    </div>
{% endblock %}

chat/templates/chats/chats_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Чаты {% endblock %}

{% block content %}
  {% include '../includes/sidebar.html' %}
    <div class='content col-xl-9 h-100'>
      <h1 class='title'>Чаты</h1>
       <button class='find-friend-btn'>
        <a href='{% url "users:users_list" %}'>Найти друга</a>
      </button>
      <input class="search-bar" type="text" placeholder="Поиск.." id="js-search">
      <div class='all-chats-list list' id="js-list-container">
        {% for chat in chats %}
           <a class='all-chats-list__item item' href='{% url "chats:chat" chat.id %}'>
             {% if chat.first_user.id == request.user.id %}
                <div class='chat__img item__img'>
                  {% if chat.second_user.profile.image %}
                      <img src='{{ chat.second_user.profile.get_image_x256.url }}'>
                  {% else %}
                      <span>{{ chat.second_user.username|make_list|first|capfirst }}</span>
                  {% endif %}
                </div>
                <span class='chat__name item__name'>
                  {{ chat.second_user.username|truncatechars:50 }}
                </span>
             {% else %}
                <div class='chat__img item__img'>
                  {% if chat.first_user.profile.image %}
                      <img src='{{ chat.first_user.profile.get_image_x256.url }}'>
                  {% else %}
                      <span>{{ chat.first_user.username|make_list|first|capfirst }}</span>
                  {% endif %}
                </div>
                <span class='chat__name item__name'>
                  {{ chat.first_user.username|truncatechars:50 }}
                </span>
             {% endif %}
            </a>
        {% endfor %}
      </div>
    </div>
    <script src="{% static 'js/search_bar.js' %}"></script>
{% endblock %}

chat/templates/chats/clear_chats_messages.html
{% extends "base.html" %}

{% load static %}

{% block title %} Чаты {% endblock %}

{% block content %}
  {% include '../includes/sidebar.html' %}
    <div class='content col-xl-9 h-100'>
      <h3 class='title'>История сообщений удалена!</h3>
      <a href="{% url 'chats:chat' chat.id %}" class='go-back-btn'><button>Перейти к чату</button></a>
    </div>
{% endblock %}