chat/chat/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('groups/', include('groups.urls', namespace="groups")),
    path('chats/', include('chats.urls', namespace="chats")),
    path('channels/', include('users_channels.urls', namespace="channels")),
    path('auth/', include('users.urls', namespace="users")),
    path('info/', include('info.urls', namespace="info")),
    path('', include('homepage.urls', namespace="homepage")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

chat/groups/urls.py
from django.urls import path

from groups.views import (ClearGroupMessagesConfirmView,
                          ClearGroupMessagesView, CreateGroupView,
                          DeleteGroupView, EditGroupView, GroupsListView,
                          GroupView)

app_name = 'groups'

urlpatterns = [
    path('to/<slug:group_slug>/',
         GroupView.as_view(),
         name='group'),
    path('create/',
         CreateGroupView.as_view(),
         name='create'),
    path('edit/<slug:group_slug>/',
         EditGroupView.as_view(),
         name='edit'),
    path('delete/<slug:group_slug>/',
         DeleteGroupView.as_view(),
         name='delete_group'),
    path('clear_messages_confirm/<slug:group_slug>/',
         ClearGroupMessagesConfirmView.as_view(),
         name='clear_messages_confirm'),
    path('clear_messages/<slug:group_slug>/',
         ClearGroupMessagesView.as_view(),
         name='clear_messages'),
    path('',
         GroupsListView.as_view(),
         name='groups_list'),
]

chat/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from users.views import ProfileView, SignupView, UserDetailView, UsersListView

app_name = 'users'

urlpatterns = [
    path('logout/',
         LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
    path('login/',
         LoginView.as_view(
             template_name='users/login.html'),
         name='login'),

    path('password_change/',
         PasswordChangeView.as_view(template_name='users/password_change.html'),
         name='password_change'),
    path('password_change/done/',
         PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),

    path('password_reset/',
         PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password_reset/done/',
         PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

    path('users/',
         UsersListView.as_view(),
         name='users_list'),
    path('users/<int:id>/',
         UserDetailView.as_view(),
         name='user_detail'),

    path('signup/',
         SignupView.as_view(),
         name='signup'),
    path('profile/',
         ProfileView.as_view(),
         name='profile'),
]

chat/groups/models.py
from core.models import BaseWebsocketGroup


class Group(BaseWebsocketGroup):
    """
    Модель Группы. Наследуется от абстрактной модели BaseWebsocketGroup 
    """
    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

chat/groups/forms.py
from core.widgets import CustomCheckboxSelectMultiple, CustomClearableFileInput
from django import forms
from django.contrib.auth import get_user_model
from django.db.models import Q

from groups.validators import validate_slug

User = get_user_model()


class CreateGroupForm(forms.Form):
    """
    Форма создания группы

    Fields:
        slug (SlugField): идентификатор
        name (CharField): имя
        group_members(ModelMultipleChoiceField): участники

    """

    def __init__(self, *args, **kwargs):
        self.user: User = kwargs.pop('user')
        super(CreateGroupForm, self).__init__(*args, **kwargs)
        self.fields['group_members'].queryset = \
            User.objects.filter(~Q(id=self.user.id)).only('id', 'username')

    slug = forms.SlugField(label='Идентификатор',
                           help_text='Используйте буквы, цифры или @/./+/-/_ ',
                           max_length=100,
                           validators=[validate_slug])

    name = forms.CharField(max_length=100,
                           label='Имя группы',
                           help_text='Максимум 100 символов',
                           required=True)

    group_members = forms.ModelMultipleChoiceField(label='Участники',
                                                   queryset=User.objects.all(),
                                                   widget=CustomCheckboxSelectMultiple(),
                                                   required=False)


class EditGroupForm(forms.Form):
    """
    Форма редактирования группы

    Fields:
        name (CharField): имя
        image (ImageField): изображение
        group_members(ModelMultipleChoiceField): участники

    """

    def __init__(self, *args, **kwargs):
        self.user: User = kwargs.pop('user')
        super(EditGroupForm, self).__init__(*args, **kwargs)
        self.fields['group_members'].queryset = \
            User.objects.filter(~Q(id=self.user.id)).only('id', 'username')

    name = forms.CharField(max_length=100,
                           label='Имя группы',
                           help_text='Максимум 100 символов',
                           required=True)

    image = forms.ImageField(label='Аватар группы',
                             required=False,
                             allow_empty_file=False,
                             widget=CustomClearableFileInput)

    group_members = forms.ModelMultipleChoiceField(label='Участники',
                                                   queryset=User.objects.all(),
                                                   widget=CustomCheckboxSelectMultiple(),
                                                   required=False)

chat/groups/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.handlers.asgi import ASGIRequest
from django.db.models import Prefetch
from django.db.models.query import QuerySet
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.decorators import method_decorator
from django.views.generic.base import TemplateView
from users_messages.models import DailyGroupMessages
from websockets.connection_types import GROUPS_CONNECTION

from groups.forms import CreateGroupForm, EditGroupForm
from groups.models import Group

User = get_user_model()


@method_decorator(login_required, name='dispatch')
class GroupView(TemplateView):
    """
    Отображает модель Group - список сообщений, панель редактирования и удаления группы,
    поле отправки сообщения

    Context:
        connection_type (str): тип подключения к вебсокетам
        is_member (bool): флаг, указывающий является ли пользователь участником группы
        user (User): экземпляр класса User
        group (Group): экземпляр класса Group
        messages (UserGroupMessage[]): сообщения группы
        members_count (int): количество участников групы

    Template:
        template_name: 'groups/group.html'

    """

    template_name = 'groups/group.html'

    def get(self, request: ASGIRequest, group_slug: str, *args, **kwargs):
        return render(request,
                      self.template_name,
                      self.get_context_data(request.user, group_slug))

    def get_context_data(self, user: User, group_slug: str, **kwargs):
        context = super().get_context_data(**kwargs)
        group: Group = get_object_or_404(Group, slug=group_slug)

        context['connection_type'] = GROUPS_CONNECTION
        context['user'] = user
        context['members_count'] = group.group_members.count()
        context['is_member'] = False

        if self._check_if_user_is_member(group, user):
            container, created = DailyGroupMessages.objects.get_or_create(group=group)

            prefetch_users = Prefetch('user', queryset=User.objects.only('username'))
            messages = container.group_messages.prefetch_related(prefetch_users)

            context['is_member'] = True
            context['group'] = group
            context['messages'] = messages

        return context

    def _check_if_user_is_member(self, group: Group, user: User) -> bool:
        return group.group_members.filter(id=user.id)


@method_decorator(login_required, name='dispatch')
class CreateGroupView(TemplateView):
    """
    Отображает форму создания группы

    Context:
        user (User): экземпляр класса User
        form (CreateGroupForm): форма создания группы

    Template:
        template_name: 'groups/create_group.html'

    Form:
        form_class: CreateGroupForm

    """

    template_name = 'groups/create_group.html'
    form_class = CreateGroupForm

    def get(self, request: ASGIRequest, *args, **kwargs):
        return render(request,
                      self.template_name,
                      self.get_context_data(request))

    def post(self, request: ASGIRequest, *args, **kwargs):
        user: User = get_object_or_404(User.objects.all(),
                                       pk=request.user.id)

        form = self.form_class(request.POST, user=user)

        if form.is_valid():
            members: QuerySet = form.cleaned_data['group_members']

            group: Group = Group(slug=form.cleaned_data['slug'],
                                 name=form.cleaned_data['name'],
                                 owner=user)
            group.save()
            group.group_members.set(members)
            group.group_members.add(user)
            group.save()

            return redirect('groups:group', form.cleaned_data['slug'])

        return self.get(request)

    def get_context_data(self, request: ASGIRequest, **kwargs):
        context = super().get_context_data(**kwargs)

        user: User = get_object_or_404(User.objects.only('email', 'username'),
                                       pk=request.user.id)

        form = self.form_class(request.POST or None, user=user)
        form.is_valid()

        context['user'] = user
        context['form'] = form

        return context


@method_decorator(login_required, name='dispatch')
class GroupsListView(TemplateView):
    """
    Отображает список групп (Group) пользователя

    Context:
        groups (Group[]): QuerySet содержащий экземпляры класса Group

    Template:
        template_name: 'groups/groups_list.html'

    """

    template_name = 'groups/groups_list.html'

    def get(self, request: ASGIRequest, *args, **kwargs):
        return render(request,
                      self.template_name,
                      self.get_context_data(request.user))

    def get_context_data(self, user: User, **kwargs):
        context = super().get_context_data(**kwargs)
        groups: QuerySet = user.users_groups.all()
        context['groups'] = groups
        return context


@method_decorator(login_required, name='dispatch')
class ClearGroupMessagesConfirmView(TemplateView):
    """
    Отображает модальное окно с подтверждением удаления истории сообщений группы

    Context:
        group (Group): экземпляр класса Group

    Template:
        template_name: 'groups/clear_group_messages_confirm.html'

    """

    template_name = 'groups/clear_group_messages_confirm.html'

    def get(self, request: ASGIRequest, group_slug: str, *args, **kwargs):
        return render(request,
                      self.template_name,
                      self.get_context_data(group_slug))

    def get_context_data(self, group_slug: str, **kwargs):
        context = super().get_context_data(**kwargs)
        group: Group = get_object_or_404(Group, pk=group_slug)
        context['group'] = group
        return context


@method_decorator(login_required, name='dispatch')
class ClearGroupMessagesView(TemplateView):
    """
    Отображает страницу с сообщением об успешном удалении истории сообщений группы

    Context:
        group (Group): экземпляр класса Group

    Template:
        template_name: 'groups/clear_group_messages.html'

    """

    template_name = 'groups/clear_group_messages.html'

    def get(self, request: ASGIRequest, group_slug: str, *args, **kwargs):
        group: Group = get_object_or_404(Group, pk=group_slug)
        group_container: DailyGroupMessages = DailyGroupMessages.objects.get(group=group)
        group_container.group_messages.all().delete()

        return render(request,
                      self.template_name,
                      self.get_context_data(group_slug))

    def get_context_data(self, group_slug: str, **kwargs):
        context = super().get_context_data(**kwargs)
        group: Group = get_object_or_404(Group, pk=group_slug)
        context['group'] = group
        return context


@method_decorator(login_required, name='dispatch')
class DeleteGroupView(TemplateView):
    template_name = 'groups/delete_group_messages.html'

    def get(self, request: ASGIRequest, group_slug: str, *args, **kwargs):
        group: Group = get_object_or_404(Group, pk=group_slug)
        group_container: DailyGroupMessages = DailyGroupMessages.objects.get(group=group)
        group_container.group_messages.all().delete()
        group.delete()

        return render(request,
                      self.template_name,
                      self.get_context_data())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


@method_decorator(login_required, name='dispatch')
class EditGroupView(TemplateView):
    """
    Отображает страницу с сообщением об успешном удалении истории сообщений группы

    Context:
        group (Group): экземпляр класса Group
        form (EditGroupForm): форма редактирования группы

    Template:
        template_name: 'groups/edit_group.html'

    Form:
        form_class (EditGroupForm): форма редактирования группы

    """

    template_name = 'groups/edit_group.html'
    form_class = EditGroupForm

    def get(self, request: ASGIRequest, group_slug: str, *args, **kwargs):
        return render(request,
                      self.template_name,
                      self.get_context_data(request, group_slug))

    def post(self, request, group_slug: str, *args, **kwargs):
        group: Group = get_object_or_404(Group.objects.all(),
                                         pk=group_slug)

        user: User = get_object_or_404(User.objects.only('id'),
                                       pk=request.user.id)

        form = self.form_class(request.POST,
                               request.FILES,
                               user=user)

        if form.is_valid() and group.owner == user:
            group.name = form.cleaned_data['name']

            members: QuerySet = form.cleaned_data['group_members']

            if members:
                group.group_members.set(members)
                group.group_members.add(user)

            group.save()

            # если нажата кнопка удаления изображения
            if form.cleaned_data['image'] is False:
                group.image = None
            else:
                group.image = form.cleaned_data['image'] or group.image

            group.save()

            return redirect('groups:group', group.slug)

        return render(request,
                      self.template_name,
                      self.get_context_data(request, group_slug))

    def get_context_data(self, request: ASGIRequest, group_slug: str, **kwargs):
        context = super().get_context_data(**kwargs)

        group: Group = get_object_or_404(Group.objects.all(),
                                         pk=group_slug)
        user: User = get_object_or_404(User.objects.only('id'),
                                       pk=request.user.id)

        initial_form_data = {

chat/templates/groups/clear_group_messages.html
{% extends "base.html" %}

{% load static %}

{% block title %} Группы {% endblock %}

{% block content %}
  {% include '../includes/sidebar.html' %}
    <div class='content col-xl-9 h-100'>
      <h3 class='title'>История сообщений удалена!</h3>
      <a href="{% url 'groups:group' group.slug %}" class='go-back-btn'><button>Перейти к группе</button></a>
    </div>
{% endblock %}

chat/templates/groups/create_group.html
{% extends "base.html" %}

{% load static %}

{% block title %} Создание группы {% endblock %}

{% block content %}
  {% include '../includes/sidebar.html' %}
    <div class='content col-xl-9 h-100'>
        <h1 class='title'>Создание группы</h1>
        {% include 'includes/form.html' with form=form submit_text="Создать группу" %}
    </div>
{% endblock %}

chat/templates/groups/delete_group_messages.html
{% extends "base.html" %}

{% load static %}

{% block title %} Группы {% endblock %}

{% block content %}
  {% include '../includes/sidebar.html' %}
    <div class='content col-xl-9 h-100'>
      <h3 class='title'>Группа удалена!</h3>
      <a href="/" class='go-back-btn'><button>На главную</button></a>
    </div>
{% endblock %}

chat/templates/groups/edit_group.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Редактирование группы
{% endblock %}

{% block content %}
    {% include '../includes/sidebar.html' %}
    <div class='content col-xl-9 h-100'>
        {% include '../includes/delete_group_confirm.html' with group=group %}
        <h1 class='title'>Редактирование группы</h1>
        {% include 'includes/form.html' with form=form submit_text="Изменить" %}
        <script type='text/javascript' src='{% static "js/delete_group_confirmation_modal.js" %}'></script>
    </div>
{% endblock %}

chat/templates/groups/group.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Группа {{ group.name|safe }} {% endblock %}

{% block content %}
  {% include '../includes/sidebar.html' %}
    <div class='content col-xl-9 h-100'>
      {% if is_member %}
        {% include '../includes/clear_group_messages_confirm.html' with group=group %}
        <h1 class='title' title='{{ group.slug }}'>Группа: {{ group.name|safe }}</h1>
        <div class='chat col-12'>
            <div class="chat__options">
                <span class="chat__group-slug">
                  {{ group.slug|safe }}
                </span>
                <div class="vl"></div>
                <div class="chat__members-count">
                  <svg viewBox="0 0 32 32"><path d="M11.33,14.44A6.22,6.22,0,1,0,5.11,8.22,6.22,6.22,0,0,0,11.33,14.44Z"/><path d="M23.78,17.56a4.67,4.67,0,1,0-4.67-4.67A4.66,4.66,0,0,0,23.78,17.56Z"/><path d="M30,28.44a1.55,1.55,0,0,0,1.56-1.55A7.79,7.79,0,0,0,19,20.74,10.9,10.9,0,0,0,.44,28.44,1.56,1.56,0,0,0,2,30H20.67a1.55,1.55,0,0,0,1.55-1.56"/></svg>
                  <span>
                    {{ members_count }}
                  </span>
                </div>
               {% if user.id == group.owner.id %}
                <a href="{% url 'groups:edit' group.slug %}" class='chat__edit'>
                  <svg viewBox="0 0 32 32"><path d="M0,31a.74.74,0,0,0,.89.88l7.26-1.76L1.66,23.63Z"/><rect x="3.26" y="12.28" width="23.3" height="9.2" transform="translate(-7.57 15.49) rotate(-44.98)"/><path d="M31.35,3.82,28.44.92a2.87,2.87,0,0,0-4.06,0L21.59,3.7l6.51,6.51L31.35,7A2.23,2.23,0,0,0,31.35,3.82Z"/></svg>
                </a>
                <a class='chat__clear-messages'>
                  <svg viewBox="0 0 32 32"><path class="cls-1" d="M17.39,16l7.32-7.32a1,1,0,1,0-1.39-1.39L16,14.61,8.68,7.29A1,1,0,1,0,7.29,8.68L14.61,16,7.29,23.32a1,1,0,1,0,1.39,1.39L16,17.39l7.32,7.32a1,1,0,0,0,1.39-1.39Z"/><path d="M16,32A16,16,0,1,1,32,16,16,16,0,0,1,16,32ZM16,2A14,14,0,1,0,30,16,14,14,0,0,0,16,2Z"/></svg>  
                </a>
              {% endif %}
                
            </div>
            <div id='chat-log'>
              <span class='chat-log__title-message-container'>
                <span>
                ✨ <a href='{% url 'users:user_detail' group.owner.id %}'>{{ group.owner.username|capfirst }}</a> создал группу {{ group.name }}! ✨
                </span>
              </span>
              {% for message in messages.all %}
                {% if message.user == user %}
                  <div class='message current-user-message'>
                    <span class='message__author'>
                      {{ message.user.username }} 
                    </span>
                    <p class='message__text'>{{ message.text|safe }}</p>
                    <span class='message__time'>{{ message.time }} </span>
                  </div>
                {% else %}
                  <div class='message'>
                    <span class='message__author'>
                      {{ message.user.username }} 
                    </span>
                    <p class='message__text'>{{message.text|safe}}</p>
                    <span class='message__time'>{{ message.time }} </span>
                  </div>
                {% endif %}
              {% endfor %}
            </div>
            <div class='chat__sendings'>
              <textarea 
                      id='chat-message-input'
                      maxlength='1024'
                      placeholder='Введите сообщение...'
                      rows='1'
                      ></textarea>
              <button id='chat-message-submit' title='Отправить сообщение'>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><polygon class="cls-1" points="30.58 16 1.42 2 8.42 16 1.42 30 30.58 16"/></svg>
              </button>
            </div>
        </div>
        <script type='text/javascript' src='{% static "js/auto_textarea_resizing.js" %}'></script>
        <script type='text/javascript' src='{% static "js/messages_confirmation_modal.js" %}'></script>
        {% include '../includes/websocket_data.html' with connection_type=connection_type connection_name=group.slug username=request.user.username %}
      {% else %}
        <h1 class='title'>Вы не состоите в этой группе 😔</h1>
      {% endif %}
    </div>
{% endblock %}

chat/templates/groups/groups_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Группы {% endblock %}

{% block content %}
  {% include '../includes/sidebar.html' %}
    <div class='content col-xl-9 h-100'>
      <h1 class='title'>Группы</h1>
      <button class='create-group-btn'>
        <a href='{% url "groups:create" %}'>Создать группу</a>
      </button>
      <input class="search-bar" type="text" placeholder="Поиск.." id="js-search">
      <div class='groups-list list' id="js-list-container">
        {% for group in groups %}
           <a class='group item' href='{% url "groups:group" group.slug %}'>
              <div class='group__img item__img'>
                  {% if group.image %}
                      <img src='{{ group.get_image_x256.url }}'>
                  {% else %}
                      <span>{{ group.name|make_list|first|capfirst  }}</span>
                  {% endif %}
              </div>
              <span class='group__name item__name'>
                {{ group.name }}
              </span>
            </a>
        {% endfor %}
      </div>
    </div>
    <script src="{% static 'js/search_bar.js' %}"></script>
{% endblock %}