chat/chat/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('groups/', include('groups.urls', namespace="groups")),
    path('chats/', include('chats.urls', namespace="chats")),
    path('channels/', include('users_channels.urls', namespace="channels")),
    path('auth/', include('users.urls', namespace="users")),
    path('info/', include('info.urls', namespace="info")),
    path('', include('homepage.urls', namespace="homepage")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

chat/chats/urls.py
from django.urls import path

from chats.views import (ChatRedirectOrCreateView, ChatsListView, ChatView,
                         ClearChatMessagesConfirmView, ClearChatMessagesView)

app_name = 'chats'

urlpatterns = [
    path('',
         ChatsListView.as_view(),
         name='chats_list'),
    path('<int:chat_id>/',
         ChatView.as_view(),
         name='chat'),
    path('clear_messages_confirm/<int:chat_id>/',
         ClearChatMessagesConfirmView.as_view(),
         name='clear_messages_confirm'),
    path('clear_messages/<int:chat_id>/',
         ClearChatMessagesView.as_view(),
         name='clear_messages'),
    path('redirect_or_create/',
         ChatRedirectOrCreateView.as_view(),
         name='redirect_or_create'),
]

chat/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from users.views import ProfileView, SignupView, UserDetailView, UsersListView

app_name = 'users'

urlpatterns = [
    path('logout/',
         LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
    path('login/',
         LoginView.as_view(
             template_name='users/login.html'),
         name='login'),

    path('password_change/',
         PasswordChangeView.as_view(template_name='users/password_change.html'),
         name='password_change'),
    path('password_change/done/',
         PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),

    path('password_reset/',
         PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password_reset/done/',
         PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

    path('users/',
         UsersListView.as_view(),
         name='users_list'),
    path('users/<int:id>/',
         UserDetailView.as_view(),
         name='user_detail'),

    path('signup/',
         SignupView.as_view(),
         name='signup'),
    path('profile/',
         ProfileView.as_view(),
         name='profile'),
]

chat/users/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.html import mark_safe
from sorl.thumbnail import get_thumbnail

User = get_user_model()


class Profile(models.Model):
    """
    Модель профиля пользователя. Расширяет модель User.

    Attributes:
        user (User): пользователь
        image (ImageField): изображение
        biography (TextField): краткая информация о пользователе

    """

    user = models.OneToOneField(User,
                                on_delete=models.CASCADE)

    biography = models.TextField(verbose_name='О себе',
                                 max_length=500,
                                 unique=False,
                                 null=True,
                                 help_text='Немного расскажите о себе')

    image = models.ImageField(verbose_name='Изображение пользователя',
                              upload_to='uploads/users_images',
                              null=True,
                              help_text='Выберите изображение')

    def get_image_x256(self):
        return get_thumbnail(self.image,
                             '256',
                             quality=51)

    def image_tmb(self):
        if self.image:
            return mark_safe(f'<img src="{self.image.url}" width="50"')
        return 'Нет изображения'

    image_tmb.short_description = 'Изображение'
    image_tmb.allow_tags = True

    class Meta:
        verbose_name = 'Дополнительное поле'
        verbose_name_plural = 'Дополнительные поля'


@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

chat/users/forms.py
from core.widgets import CustomClearableFileInput
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.password_validation import validate_password
from users.validators import validate_email, validate_login

User = get_user_model()


class EditProfileForm(forms.Form):
    """
    Форма редактирования профиля пользователя

    Fields:
        login (CharField): имя пользователя
        email (EmailField): электронная почта
        image (ImageField): изображение
        biography (CharField): краткая информация о пользователе

    """

    login = forms.CharField(max_length=150,
                            label='Имя пользователя',
                            help_text='Максимум 150 символов',
                            required=True)

    email = forms.EmailField(label='Почта',
                             required=False)

    image = forms.ImageField(label='Аватар',
                             required=False,
                             allow_empty_file=False,
                             widget=CustomClearableFileInput)

    biography = forms.CharField(label='Расскажите немного о себе',
                                widget=forms.Textarea(),
                                max_length=500,
                                required=False)

    def validate_edit_login(self, current_user):
        login = self.cleaned_data['login']

        if len(login.strip()) < 2:
            self.add_error('login', 'Длина имени не менее 2 символов!')
            return

        if login != current_user.username and User.objects.filter(username=login):
            self.add_error('login',
                           'Пользователь с таким именем уже существует!')
            return

        return True

    def validate_edit_email(self, current_user):
        email = self.cleaned_data['email']

        if email != current_user.email and User.objects.filter(email=email):
            self.add_error('email',
                           'Пользователь с такой почтой уже существует!')
            return

        return True

    def validate_all(self, current_user):
        return self.validate_edit_email(current_user) and self.validate_edit_login(current_user)


class SignupForm(forms.Form):
    """
    Форма регистрации

    Fields:
        login (CharField): имя пользователя
        email (EmailField): электронная почта
        password (CharField): пароль
        password_repeat (CharField): еще раз пароль

    """
    email = forms.CharField(max_length=200,
                            label='Адрес электронной почты',
                            widget=forms.EmailInput,
                            required=True,
                            validators=[validate_email])
    login = forms.CharField(max_length=150,
                            label='Имя пользователя',
                            help_text='Максимум 150 символов',
                            required=True,
                            validators=[validate_login])
    password = forms.CharField(max_length=255, label='Пароль',
                               help_text='Максимум 255 символов',
                               widget=forms.PasswordInput,
                               required=True,
                               min_length=8,
                               validators=[validate_password])
    password_repeat = forms.CharField(max_length=255,
                                      label='Повторите пароль',
                                      widget=forms.PasswordInput)

    def check_passwords_match(self):
        password = self.cleaned_data['password']
        password_repeat = self.cleaned_data['password_repeat']

        if password != password_repeat:
            self.add_error('password', 'Пароли не совпадают!')
            return
        return password

chat/users/views.py
from django.contrib.auth import get_user_model, login
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.decorators import method_decorator
from django.views.generic.base import TemplateView

from users.forms import EditProfileForm, SignupForm

User = get_user_model()


class UsersListView(TemplateView):
    """
    Отображает список пользователей

    Context:
        users (User[]): QuerySet, содержащий экземпляры класса User

    Template:
        template_name: 'users/users_list.html'

    """

    template_name = 'users/users_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        users = User.objects.only('id', 'username')
        context['users'] = users
        return context


@method_decorator(login_required, name='dispatch')
class UserDetailView(TemplateView):
    """
    Отображает страницу пользователя (User)

    Context:
        user (User): экземпляр класса User

    Template:
        template_name: 'users/users_list.html'

    """
    template_name = 'users/user_detail.html'

    def get(self, request, id: int, *args, **kwargs):
        if request.user.id == id:
            return redirect('users:profile')
        else:
            return render(request,
                          self.template_name,
                          self.get_context_data(id))

    def get_context_data(self, id: int, **kwargs):
        context = super().get_context_data(**kwargs)
        user: User = get_object_or_404(User.objects.only('email', 'username'), pk=id)
        context['user'] = user
        return context


@method_decorator(login_required, name='dispatch')
class ProfileView(TemplateView):
    """
    Отображает страницу редактирования профиля пользователя.

    Context:
        user (User): экземпляр класса User
        form (EditProfileForm): форма редактирования профиля

    Template:
        template_name: 'users/profile.html'

    Form:
        form_class (EditProfileForm): форма редактирования профиля

    """

    template_name = 'users/profile.html'
    form_class = EditProfileForm

    def get(self, request, *args, **kwargs):
        return render(request,
                      self.template_name,
                      self.get_context_data(request))

    def post(self, request, *args, **kwargs):
        user: User = get_object_or_404(User.objects.only('email', 'username'),
                                       pk=request.user.id)

        form = self.form_class(request.POST, request.FILES)

        if form.is_valid() and form.validate_all(request.user):
            user.email = form.cleaned_data['email']
            user.username = form.cleaned_data['login']
            user.profile.biography = form.cleaned_data['biography'] or user.profile.biography

            # если нажат чекбокс очистки изображения
            if form.cleaned_data['image'] is False:
                user.profile.image = None
            else:
                user.profile.image = form.cleaned_data['image'] or user.profile.image

            user.save()

            return redirect('users:profile')

        return render(request,
                      self.template_name,
                      self.get_context_data(request))

    def get_context_data(self, request, **kwargs):
        context = super().get_context_data(**kwargs)

        user: User = get_object_or_404(User.objects.only('email', 'username'),
                                       pk=request.user.id)

        initial_form_data = {
            'email': user.email,
            'login': user.username,
            'biography': user.profile.biography,
            'image': user.profile.image
        }
        form = self.form_class(request.POST or None,
                               request.FILES or None,
                               initial=initial_form_data)
        # небоходимо, чтобы показать ошибки валидации формы
        if form.is_valid():
            form.validate_all(user)

        context['user'] = user
        context['form'] = form

        return context


class SignupView(TemplateView):
    """
    Отображает страницу регистрации

    Context:
        form (SignupForm): форма регистрации

    Template:
        template_name: 'users/signup.html'

    Form:
        form_class (SignupForm): форма регистрации

    """
    template_name = 'users/signup.html'
    form_class = SignupForm

    def get(self, request, *args, **kwargs):
        return render(request,
                      self.template_name,
                      self.get_context_data(request))

    def post(self, request, *args, **kwargs):
        context = self.get_context_data(request)

        form = context['form']

        if form.is_valid() and form.check_passwords_match():
            user: User = User.objects.create_user(
                username=form.cleaned_data['login'],
                password=form.cleaned_data['password'],
                email=form.cleaned_data['email']
            )

            login(request, user)

            return redirect('homepage:home')

        return render(request,
                      self.template_name,
                      self.get_context_data(request))

    def get_context_data(self, request, **kwargs):
        context = super().get_context_data(**kwargs)
        form = self.form_class(request.POST or None)
        context['form'] = form
        # небоходимо, чтобы показать ошибки валидации формы
        form.is_valid() and form.check_passwords_match()
        return context

chat/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}
    Выход
{% endblock %}

{% block content %}
    <h1 class='title'>Вы вышли из аккаунта 😔</h1>
{% endblock %}

chat/templates/users/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Вход
{% endblock %}

{% block content %}
<div class='content container-fluid h-100'>
    <h1 class='title'>
        Вход в <img class="img img-responsive title__img" src="{% static './img/text_logo.svg' %}" alt="Soft Logo">
    </h1>
    {% include 'includes/form.html' with form=form submit_text="Войти" show_forgot_password=True show_register_link=True %}
</div>

{% endblock %}

chat/templates/users/password_change.html
{% extends 'base.html' %}
{% block title %}
    Смена пароля
{% endblock %}

{% block content %}
<h1 class='title'>Сменить пароль</h1>
{% include 'includes/form.html' with form=form submit_text="Изменить пароль" %}
{% endblock %}

chat/templates/users/password_change_done.html
{% extends 'base.html' %}
{% block title %}
    Смена пароля
{% endblock %}

{% block content %}
<h1 class='title'>Вы успешно сменили пароль!</h1>
{% endblock %}

chat/templates/users/password_reset.html
{% extends 'base.html' %}
{% block title %}
    Восстановление пароля
{% endblock %}

{% block content %}
    <h1 class='title'>Восстановление пароля</h1>
    {% include 'includes/form.html' with form=form submit_text="Восстановить пароль" %}
{% endblock %}

chat/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% block title %}
    Восстановление пароля завершено
{% endblock %}

{% block content %}
    <h1 class='title'>Восстановление пароля завершено</h1>
    <p>
        Ваш пароль был сохранен. Теперь вы можете войти.
    </p>
    <p>
        <a href='/auth/login'>Войти</a>
    </p>
{% endblock %}

chat/templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% block title %}
    Подтверждение 
{% endblock %}

{% block content %}
    {% if form %}
    <h1 class='title'>Подтверждение</h1>
    {% include 'includes/form.html' with form=form submit_text="Восстановить пароль" %}
    {% else %}
    <h1 class='title'>Ошибка восстановления пароля</h1>
    <p>
        Неверная ссылка для восстановления пароля. Возможно, ей уже воспользовались. Пожалуйста, попробуйте восстановить пароль еще раз.
    </p>
    {% endif %}
{% endblock %}

chat/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% block title %}
    Восстановление пароля
{% endblock %}

{% block content %}
    <h1 class='title'>Письмо с инструкциями по восстановлению пароля отправлено</h1>
    <p>
    Мы отправили вам инструкцию по установке нового пароля на указанный адрес электронной почты (если в нашей базе данных есть такой адрес). Вы должны получить ее в ближайшее время.

    Если вы не получили письмо, пожалуйста, убедитесь, что вы ввели адрес с которым Вы зарегистрировались, и проверьте папку со спамом.
    </p>
{% endblock %}

chat/templates/users/profile.html
{% extends 'base.html' %}

{% block title %}
    Мой профиль
{% endblock %}

{% block content %}
    {% include '../includes/sidebar.html' %}
    <div class='content col-xl-9 h-100'>
        <h1 class='title'>Мой профиль</h1>
        {% include 'includes/form.html' with form=form submit_text="Изменить" %}
    </div>
{% endblock %}

chat/templates/users/signup.html
{% extends 'base.html' %}

{% block title %}
    Регистрация
{% endblock %}

{% block content %}
    <div class='content container-fluid h-100'>
        <h1 class='title'>Регистрация</h1>
        {% include 'includes/form.html' with form=form submit_text="Зарегистрироваться" show_already_have_account=True %}
    </div>
{% endblock %}

chat/templates/users/user_detail.html
{% extends 'base.html' %}

{% block title %}
    Профиль {{ user.username|safe }}
{% endblock %}

{% block content %}
    {% include '../includes/sidebar.html' %}
    <div class='content col-12 col-xl-9 h-100'>
        <h1 class='title'>Профиль пользователя {{ user.username|safe }}</h1>
        <div class='user-detail-container col-12'>
            <div class='user-info'>
                <div class='user-info__top'>
                    <div class='user-img user-info__img'>
                        {% if user.profile.image %}
                            <img src='{{ user.profile.get_image_x256.url }}' alt='user image' class='img img-responsive'>
                        {% else %}
                            <span>{{ user.username|make_list|first|capfirst  }}</span>
                        {% endif %}
                    </div>
                    <span class='user-info__name'>{{user.username}}</span>
                </div>
                {% if user.email %}
                    <div class="user-info__row">
                        <span class='user-info__value user-info__email'>{{user.email}}</span>
                        <span class="user-info__row-title">
                            Почта
                        </span>
                    </div>
                {% endif %}
                {% if user.profile.biography %}
                    <div class="user-info__row">
                        <span class='user-info__value user-info__bio'>{{user.profile.biography}}</span>
                        <span class="user-info__row-title">
                            О себе
                        </span>
                    </div>
                {% endif %}
                <a href="{% url 'chats:redirect_or_create'%}?username={{user.username}}">
                    <button>
                        Написать
                    </button>
                </a>
            </div>
        </div>
        
    </div>
{% endblock %}

chat/templates/users/users_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Список пользователей
{% endblock %}

{% block content %}

    {% include '../includes/sidebar.html' %}
    <div class='content col-xl-9 h-100'>
        <h1 class='title'>Список пользователей</h1>
        <input class="search-bar" type="text" placeholder="Поиск.." id="js-search">
        <div class='users-list' id="js-list-container">
            {% for user_list in users %}
                <a class='all-chats-list__item item' href='{% url "users:user_detail" user_list.id %}'>
                    <div class='chat__img item__img'>
                        {% if user_list.profile.image %}
                            <img src='{{ user_list.profile.get_image_x256.url }}'>
                        {% else %}
                            <span>{{ user_list.username|make_list|first|capfirst }}</span>
                        {% endif %}
                    </div>
                    <span class='chat__name item__name'>
                        {{ user_list.username|truncatechars:50 }}
                    </span>
                </a>
                
            {% endfor %}
        </div>
    </div>
    <script src="{% static 'js/search_bar.js' %}"></script>

{% endblock %}


 