chat/chat/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('groups/', include('groups.urls', namespace="groups")),
    path('chats/', include('chats.urls', namespace="chats")),
    path('channels/', include('users_channels.urls', namespace="channels")),
    path('auth/', include('users.urls', namespace="users")),
    path('info/', include('info.urls', namespace="info")),
    path('', include('homepage.urls', namespace="homepage")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

chat/chats/urls.py
from django.urls import path

from chats.views import (ChatRedirectOrCreateView, ChatsListView, ChatView,
                         ClearChatMessagesConfirmView, ClearChatMessagesView)

app_name = 'chats'

urlpatterns = [
    path('',
         ChatsListView.as_view(),
         name='chats_list'),
    path('<int:chat_id>/',
         ChatView.as_view(),
         name='chat'),
    path('clear_messages_confirm/<int:chat_id>/',
         ClearChatMessagesConfirmView.as_view(),
         name='clear_messages_confirm'),
    path('clear_messages/<int:chat_id>/',
         ClearChatMessagesView.as_view(),
         name='clear_messages'),
    path('redirect_or_create/',
         ChatRedirectOrCreateView.as_view(),
         name='redirect_or_create'),
]

chat/groups/urls.py
from django.urls import path

from groups.views import (ClearGroupMessagesConfirmView,
                          ClearGroupMessagesView, CreateGroupView,
                          DeleteGroupView, EditGroupView, GroupsListView,
                          GroupView)

app_name = 'groups'

urlpatterns = [
    path('to/<slug:group_slug>/',
         GroupView.as_view(),
         name='group'),
    path('create/',
         CreateGroupView.as_view(),
         name='create'),
    path('edit/<slug:group_slug>/',
         EditGroupView.as_view(),
         name='edit'),
    path('delete/<slug:group_slug>/',
         DeleteGroupView.as_view(),
         name='delete_group'),
    path('clear_messages_confirm/<slug:group_slug>/',
         ClearGroupMessagesConfirmView.as_view(),
         name='clear_messages_confirm'),
    path('clear_messages/<slug:group_slug>/',
         ClearGroupMessagesView.as_view(),
         name='clear_messages'),
    path('',
         GroupsListView.as_view(),
         name='groups_list'),
]

chat/info/urls.py
from django.urls import path

from info.views import AboutView, InstructionView

app_name = 'info'

urlpatterns = [
    path('about',
         AboutView.as_view(),
         name='about'),
    path('instruction',
         InstructionView.as_view(),
         name='instruction'),
]

chat/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from users.views import ProfileView, SignupView, UserDetailView, UsersListView

app_name = 'users'

urlpatterns = [
    path('logout/',
         LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
    path('login/',
         LoginView.as_view(
             template_name='users/login.html'),
         name='login'),

    path('password_change/',
         PasswordChangeView.as_view(template_name='users/password_change.html'),
         name='password_change'),
    path('password_change/done/',
         PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),

    path('password_reset/',
         PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password_reset/done/',
         PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

    path('users/',
         UsersListView.as_view(),
         name='users_list'),
    path('users/<int:id>/',
         UserDetailView.as_view(),
         name='user_detail'),

    path('signup/',
         SignupView.as_view(),
         name='signup'),
    path('profile/',
         ProfileView.as_view(),
         name='profile'),
]

chat/templates/includes/checkbox_select.html
<input type="text" id="js-search" class='search-input' placeholder='Поиск...'>
<div id="js-checkboxes-list-container">
    {% include "django/forms/widgets/multiple_input.html" %}
</div>

chat/templates/includes/clear_chat_messages_confirm.html
<div class='confirmation'>
  {% include '../includes/confirmation_top.html'%}
  <div class="confirmation__bg"></div>
  <div class='confirmation__text-container content h-100'>
    <h3 class='title'>Удалить историю сообщений чата?</h3>
    <div class='clear_messages_confirm'>
      <a href="{% url 'chats:clear_messages' chat.id %}">
        <button>Да</button>
      </a>
      <a class='close-btn'>
        <button>Нет</button>
      </a>
    </div>
  </div>
</div>

chat/templates/includes/clear_group_messages_confirm.html
<div class='confirmation'>
  {% include '../includes/confirmation_top.html'%}
  <div class="confirmation__bg"></div>
  <div class='confirmation__text-container content h-100'>
    <h3 class='title'>Удалить историю сообщений группы <span class="group-name">{{ group.name }}</span>?</h3>
    <div class="clear_messages_confirm">
      <a href="{% url 'groups:clear_messages' group.slug %}">
        <button>Да</button>
      </a>
      <a class="close-btn">
        <button>Нет</button>
      </a>
    </div>
  </div>
</div>

chat/templates/includes/clearable_file_input.html
{% if widget.is_initial %}
    <a href="{{ widget.value.url }}" class="base-form__image-link">Посмотреть изображение</a>
    {% if not widget.required %}
        <div class="clear-image-block">
            <input type="checkbox" name="{{ widget.checkbox_name }}" id="{{ widget.checkbox_id }}"{% if widget.attrs.disabled %} disabled{% endif %}>
            <label for="{{ widget.checkbox_id }}">{{ widget.clear_checkbox_label }}</label>
        </div>
    {% endif %}
{% endif %}
<input type="{{ widget.type }}" name="{{ widget.name }}"{% include "django/forms/widgets/attrs.html" %}>

chat/templates/includes/confirmation_top.html
<div class='confirmation-top'>
    <span class="chat__group-slug">
      Подтверждение
    </span>
    <a class='close-confirm'>
      <svg viewBox="0 0 32 32"><path class="cls-1" d="M17.39,16l7.32-7.32a1,1,0,1,0-1.39-1.39L16,14.61,8.68,7.29A1,1,0,1,0,7.29,8.68L14.61,16,7.29,23.32a1,1,0,1,0,1.39,1.39L16,17.39l7.32,7.32a1,1,0,0,0,1.39-1.39Z"/><path d="M16,32A16,16,0,1,1,32,16,16,16,0,0,1,16,32ZM16,2A14,14,0,1,0,30,16,14,14,0,0,0,16,2Z"/></svg>  
    </a>
  </div>

chat/templates/includes/delete_group_confirm.html
<div class='confirmation'>
    {% include '../includes/confirmation_top.html'%}
    <div class="confirmation__bg"></div>
    <div class='confirmation__text-container content h-100'>
      <h3 class='title'>Удалить группу?</h3>
      <div class='clear_messages_confirm'>
        <a href="{% url 'groups:delete_group' group.slug %}">
          <button>Да</button>
        </a>
        <a class='close-btn'>
          <button>Нет</button>
        </a>
      </div>
    </div>
  </div>

chat/templates/includes/form.html
<div class='base-form col-12 col-sm-10 col-md-9 col-lg-9 col-xl-6'>
    {% load static %}
    <div class='base-form__errors'>
        {% if form.errors %}
            {% for error in form.non_field_errors %}
                <span>{{ error|escape }}</span>
            {% endfor %}
        {% endif %}
    </div>

    <form method='POST' class='base-form__form' {% if form.is_multipart %} enctype="multipart/form-data" {% endif %}>
    {% csrf_token %}

        {% for field in form %}
            <div class='base-form__form-row'>
                <label for='{{ field.id_for_label }}'>
                    {{ field.label }}
                    {% if field.field.required %}
                        <span class='base-form__star'>*</span>
                    {% endif %}
                </label>
                <div class="base-form__field-errors">
                    {% for error in field.errors %}
                        <span>{{ error|escape }}</span>
                    {% endfor %}
                </div>
                {{ field }}
                {% if field.help_text %}
                    <small id='{{ field.id_for_label}}-help'>
                        {{ field.help_text|safe}}
                    </small>
                {% endif %}
            </div>
        {% endfor %}

        <div class='form-buttons-container'>
            <button name='edit' type='submit' class='submit-btn'>{{ submit_text }}</button>
            {% if edit %}
                <button type='button' class='submit-btn delete-btn'>Удалить</button>
            {% endif %}
        </div>
        {% if show_forgot_password %}
            <span class='base-form__link'>
                <a href='{% url "users:password_reset" %}'>Забыли пароль?</a>
            </span>
        {% endif %}
        {% if show_register_link %}
            <span class='base-form__link'>
                Первый раз в <b>Soft</b>?  <a href='{% url "users:signup" %}'>Создать аккаунт!</a>
            </span>
        {% endif %}
        {% if show_already_have_account %}
            <span class='base-form__link'>
                Уже есть аккаунт? <a href='{% url "users:login" %}'>Войти</a>
            </span>
        {% endif %}
    </form>
    <script src="{% static 'js/disable_file_input_on_clear.js' %}"></script>
    <script src="{% static 'js/search.js' %}"></script>
</div>

chat/templates/includes/homepage_content.html
{% load static %}

<h1 class='title'>
    Добро пожаловать в <img class="img img-responsive title__img" src="{% static './img/text_logo.svg' %}" alt="Soft Logo">
</h1>
<p class='description'>
    Это текстовый чат, основанный на веб-сокетах. Пользователи могут общаться друг с другом, а также создавать группы. 
</p>

{% if request.user.is_authenticated %}
    <p class='description'>
        Откройте меню, чтобы создать группу или пообщаться с кем-нибудь!  
    </p>
{% else %}
    <p>
        <a href="{% url 'info:about' %}">О проекте</a>
    </p>
    <p>
        <a href="{% url 'info:instruction' %}">Инструкция</a>
    </p>
    <p class='description'>
        Авторизуйтесь, чтобы попробовать!  
    </p> 
{% endif %}

chat/templates/includes/sidebar.html
{% load static %}

<div class="sidebar col-lg-12 col-xl-3">
    {% if request.user.is_authenticated %}
        <a href="{% url 'homepage:home' %}">
            <img src="{% static './img/text_logo.svg '%}" alt="Soft logo" class="sidebar__logo img img-responsive col-6 col-md-3 col-lg-3 col-xl-6">
        </a>
        <div class="sidebar__container">
            <div class="user-block">
                <div class="user-img">
                    {% if request.user.profile.image %}
                        <img src="{{ request.user.profile.get_image_x256.url }}" alt="user image" class="img img-responsive ">
                    {% else %}
                        <span>{{ request.user.username|make_list|first|capfirst  }}</span>
                    {% endif %}
                </div>
                <div class="user">
                    <a class="user__username" href="{% url 'users:profile' %}">
                         {{ request.user.username|safe|truncatechars:50 }}
                    </a>
                    <a href="{% url 'users:logout' %}" class="logout-btn">Выйти</a>
                </div>
            </div>
            <div class="hr"></div>
            <div class="menu-container">
                
                <div id='js-menu-btn' class='menu-btn'>
                    <div class='menu-ico menu-ico_arrow'>
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><path d="M23.89,14.75l0,0a1.33,1.33,0,0,0-.3-.23l-13-13a1.7,1.7,0,0,0-2.43,0l0,0A1.73,1.73,0,0,0,8.11,4l12,12-12,12a1.73,1.73,0,0,0,0,2.44l0,0a1.7,1.7,0,0,0,2.43,0l13-13a1.33,1.33,0,0,0,.3-.23l0,0a1.81,1.81,0,0,0,0-2.5Z"/></svg>
                    </div>
                </div>

                <div class="menu">
                    <nav id="js-menu-nav">

                        <div class="nav-block">
                            <span class="nav-block__title">
                                <a href="{% url 'chats:chats_list' %}">Чаты</a>
                            </span>
                        </div>

                        <div class="nav-block">
                            <span class="nav-block__title">
                                <a href="{% url 'groups:groups_list' %}">Группы</a>
                            </span>
                        </div>

                        <div class="nav-block">
                            <span class="nav-block__title">
                                Каналы
                            </span>
                        </div>

                        {% if request.user.is_staff %}
                            <div class="nav-block">
                                <span class="nav-block__title nav-block__title_admin">
                                    <a href="{% url 'admin:index' %}">Админка</a>
                                </span>
                            </div>
                        {% endif %}

                        <div class="nav-block">
                            <span class="nav-block__title">
                                <a href="{% url 'info:about' %}">О проекте</a>
                            </span>
                        </div>
                        <div class="nav-block">
                            <span class="nav-block__title">
                                <a href="{% url 'info:instruction' %}">Инструкция</a>
                            </span>
                        </div>

                    </nav>
                </div>
            </div>
        </div>
        {% with request.resolver_match.kwargs as kwargs %}
            <div class="chats-list" id="js-chats-list">
                {% for chat in request.user.first_user_chats.all %}
                    <a class="chats-list-item
                        {% if kwargs.chat_id == chat.id %}
                            chats-list-item_active 
                        {% endif %}"
                        href="{% url 'chats:chat' chat.id %}">
                        {% if chat.first_user.id == request.user.id %}   
                            <div class="chats-list-item__img">
                                {% if chat.second_user.profile.image %}
                                    <img src="{{ chat.second_user.profile.image.url }}">
                                {% else %}
                                    <span>{{ chat.second_user.username|make_list|first|capfirst }}</span>
                                {% endif %}
                            </div>
                            <span class="chats-list-item__name">{{ chat.second_user.username|truncatechars:20 }}</span>
                        {% else %}
                            
                            <div class="chats-list-item__img">
                                {% if chat.first_user.profile.image %}
                                    <img src="{{ chat.first_user.profile.image.url }}">
                                {% else %}
                                    <span>{{ chat.first_user.username|make_list|first|capfirst }}</span>
                                {% endif %}
                            </div>
                            <span class="chats-list-item__name">{{ chat.first_user.username|truncatechars:20 }}</span>
                        {% endif %}
                    </a>
                {% endfor %}

                {% for chat in request.user.second_user_chats.all %}
                    <a class="chats-list-item
                        {% if kwargs.chat_id == chat.id %}
                            chats-list-item_active 
                        {% endif %}"
                        href="{% url 'chats:chat' chat.id %}">
                        {% if chat.first_user.id == request.user.id %}
                            <div class="chats-list-item__img">
                                {% if chat.second_user.profile.image %}
                                    <img src="{{ chat.second_user.profile.image.url }}">
                                {% else %}
                                    <span>{{ chat.second_user.username|make_list|first|capfirst }}</span>
                                {% endif %}
                            </div>
                            <span class="chats-list-item__name">{{ chat.second_user.username|truncatechars:20 }}</span>
                        {% else %}
                            <div class="chats-list-item__img">
                                {% if chat.first_user.profile.image %}
                                    <img src="{{ chat.first_user.profile.image.url }}">
                                {% else %}
                                    <span>{{ chat.first_user.username|make_list|first|capfirst }}</span>
                                {% endif %}
                            </div>
                            <span class="chats-list-item__name">{{ chat.first_user.username|truncatechars:20 }}</span>
                        {% endif %}
                    </a>
                {% endfor %}

                {% for group in request.user.users_groups.all %}
                    <a class="chats-list-item
                        {% if kwargs.group_slug == group.slug %}
                            chats-list-item_active 
                        {% endif %}"
                        href="{% url 'groups:group' group.slug %}">
                        <div class="chats-list-item__img">
                            {% if group.image %}
                                <img src="{{ group.get_image_x256.url }}">
                            {% else %}
                                <span>{{ group.name|make_list|first|capfirst  }}</span>
                            {% endif %}
                        </div>
                        <span class="chats-list-item__name">
                            <svg viewBox="0 0 32 32"><path d="M11.33,14.44A6.22,6.22,0,1,0,5.11,8.22,6.22,6.22,0,0,0,11.33,14.44Z"/><path d="M23.78,17.56a4.67,4.67,0,1,0-4.67-4.67A4.66,4.66,0,0,0,23.78,17.56Z"/><path d="M30,28.44a1.55,1.55,0,0,0,1.56-1.55A7.79,7.79,0,0,0,19,20.74,10.9,10.9,0,0,0,.44,28.44,1.56,1.56,0,0,0,2,30H20.67a1.55,1.55,0,0,0,1.55-1.56"/></svg>
                            <span>
                                {{ group.name }}
                            </span>
                        </span>
                    </a>
                {% endfor %}
                
            </div>
        {% endwith %}

    {% else %}
        <div class="btns-container">
            <a href="{% url 'users:signup' %}" class="signup-btn submit-btn">Зарегистрироваться</a>
            <a href="{% url 'users:login' %}" class="login-btn submit-btn">Войти</a>
        </div>
    {% endif %}
    <script src="{% static 'js/menu.js' %}"></script>
</div>

chat/templates/includes/websocket_data.html
{% load static %}

{{ connection_name|json_script:"connection_name" }}
{{ connection_type|json_script:"connection_type" }}
{{ username|json_script:"username" }}

<script src="{% static 'js/sockets.js' %}">
</script>